### ISSUE TITLE
save hadamard or zonal in the cube fits header

### ISSUE THREAD

**Issue by lbusoni** [ArcetriAdaptiveOptics/plico_dm_characterization#3]

**Comment by ChiaraSelmi** [comment]
Attualmente il codice già salva questa informazione dell'header del cubo con il parametro header['CMDMTAG'] = self._cmdMatrixTag che corrisponde al tag della matrice di comandi utilizzata. Poichè questo nome è arbitrario per l'utente non ho un modo per usare l'informazione nella fase di spianamento.

Quindi ho bisogno che sia l'utente a specificare cosa sta facendo:
- o al momento dello spianamento (come è scritto adesso il codice)
- o al momento dell'acquisizione (così poi salvo un parametro scelto da me da poter rileggere)

@lbusoni , quale delle due opzioni è la migliore?

**Comment by ChiaraSelmi** [comment]
Informazione salvata nel cubo al momento dell'acquisizione e ricaricata nel converter come cc._type
